# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ee8783a194b3bdd520c3cbdede0dcc09eb58166f829eb1c857588585a07ff7e200cc00a007279714389fd5c4239825d6c91406886551d01b9dbcf3a4491074

test:
  secret_key_base: a19b4d5785acfdc27c01ee16d036e3b625128e4ed9cca9f5a523dd4207a02fbe623e67cf35a612238c6e06976cf1cd008bbd7c1d0ad0c86f69a20ba55e47ebcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
